
package me.dokollari.course.manager.swings;

import java.awt.Frame;

import javax.swing.JTextField;

import me.dokollari.course.manager.Controller;
import me.dokollari.course.manager.Verify;


/**
 *
 * @author Rizart Dokollari
 */
public class JD_EditInstructors extends javax.swing.JDialog {
    private Controller controller;
    private final String FIRST_NAME_REQ = "First Name (required)";
    private final String LAST_NAME_REQ = "Last Name (required)";
    private final String PHONE = "Phone";
    private final String EMAIL = "Email";

    /** Creates new form JD_EditInstructors */
    public JD_EditInstructors(java.awt.Frame parent, boolean modal, Controller controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        initFinalCompon(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTF_firstName = new javax.swing.JTextField();
        jTF_lastName = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jB_register = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jB_back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jL_dbMessages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Instructor"));

        jTF_firstName.setForeground(new java.awt.Color(204, 204, 204));
        jTF_firstName.setText(FIRST_NAME_REQ);
        jTF_firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_firstNameFocusLost(evt);
            }
        });

        jTF_lastName.setForeground(new java.awt.Color(204, 204, 204));
        jTF_lastName.setText(LAST_NAME_REQ);
        jTF_lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTF_lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTF_lastNameFocusLost(evt);
            }
        });

        jTextField3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3.setText(PHONE);

        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText(EMAIL);

        jB_register.setBackground(new java.awt.Color(153, 255, 153));
        jB_register.setText("Register");
        jB_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_firstName)
                    .addComponent(jTF_lastName)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 149, Short.MAX_VALUE)
                .addComponent(jB_register)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTF_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jB_register)
                .addGap(20, 20, 20))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Instructors on database"));

        jB_back.setText("Back");
        jB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Sort by"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Last Name", "ID", "Name" }));

        jCheckBox1.setText("Reversed");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(267, 223));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        jL_dbMessages.setText("System:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jB_back)
                        .addGap(33, 33, 33)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jL_dbMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_back)
                        .addComponent(jL_dbMessages))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_backActionPerformed

    private void jB_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_registerActionPerformed
        String lastName = jTF_lastName.getText();
        String firstName = jTF_firstName.getText();

        try {
            controller.addInstructor(lastName, firstName, jL_dbMessages);
            reset_jTF_firstName();
            reset_jTF_lasttName();
        } catch (Exception e) {
            jL_dbMessages.setText("System: Error Occurred. Hover for details.");
            jL_dbMessages.setForeground(new java.awt.Color(255, 0, 0)); // red/error
            jL_dbMessages.setToolTipText(e.getMessage());
        }        
    }//GEN-LAST:event_jB_registerActionPerformed

    private void jTF_firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_firstNameFocusGained
        resetTextFieldGainFocus(jTF_firstName);
    }//GEN-LAST:event_jTF_firstNameFocusGained

    private void jTF_firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_firstNameFocusLost
        String text = jTF_firstName.getText();

        if (text.equals("")) {
            reset_jTF_firstName();
        } else {
            resetTextFieldLoseFocus(jTF_firstName);
        } // end else
    }//GEN-LAST:event_jTF_firstNameFocusLost

    private void jTF_lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_lastNameFocusGained
        resetTextFieldGainFocus(jTF_lastName);
    }//GEN-LAST:event_jTF_lastNameFocusGained

    private void jTF_lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTF_lastNameFocusLost
        String text = jTF_lastName.getText();

        if (text.equals("")) {
          reset_jTF_lasttName();
        } else {
            resetTextFieldLoseFocus(jTF_lastName);
        } // end else
    }//GEN-LAST:event_jTF_lastNameFocusLost

    private void initFinalCompon(Frame parent) {
        jB_back.requestFocus(); // request focus to this button.
        this.setLocationRelativeTo(parent);
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_back;
    private javax.swing.JButton jB_register;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jL_dbMessages;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_firstName;
    private javax.swing.JTextField jTF_lastName;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables


    /**
     * when given field gains focus clears textfield for user to enter text
     * @param jTF_field
     */
    private void resetTextFieldGainFocus(JTextField jTF_field) {
        if (jTF_field.getText().equals(FIRST_NAME_REQ) || jTF_field.getText().equals(LAST_NAME_REQ) ||
            jTF_field.getText().equals(Verify.NAME_REQ)) {
            jTF_field.setText("");
        }
        jTF_field.setForeground(new java.awt.Color(51, 51, 51)); // grey/default
    }

    /**
     * when given jtextfield loses focus checks if given variable is proper (alphabetical 1-45 lentth)
     * @param jTF_field
     */
    private void resetTextFieldLoseFocus(JTextField jTF_field) {
        String name = jTF_field.getText();

        try {
            Verify.checkName(name);
            jTF_field.setForeground(new java.awt.Color(0, 153, 51)); // green/correct
        } catch (Exception e) {
            jTF_field.setText(e.getMessage());
            jTF_field.setForeground(new java.awt.Color(255, 0, 0)); // red/error
        }
    }

    private void reset_jTF_firstName() {
        jTF_firstName.setText(FIRST_NAME_REQ);
        jTF_firstName.setForeground(new java.awt.Color(204, 204, 204)); // grey/default
    }
    
    private void reset_jTF_lasttName() {
        jTF_lastName.setText(LAST_NAME_REQ);
        jTF_lastName.setForeground(new java.awt.Color(204, 204, 204)); // grey/default
    }
}
