package me.dokollari.course.manager.models;

import java.io.Serializable;


/** @author Rizart Dokollari
 * @since November, 2012
 */

public class Instructor extends Person implements Serializable {
    @SuppressWarnings("compatibility:-8580673596708373092")
    private static final long serialVersionUID = 1176750091803057767L;

    /**
     * Used when data is taken form database. id is autogenerated from database.
     * @param lastName
     * @param firstName
     * @param id
     * @throws Exception
     */
    public Instructor(String lastName, String firstName, int id) throws Exception {
        super(lastName, firstName, id);
    }

    /**
     *  Used before adding to database.
     * @param lastName
     * @param firstName
     */
    public Instructor(String lastName, String firstName) throws Exception {
        super(lastName, firstName);
    }

    @Override
    public String toString() {
        return String.format("Prof. %-20s  %-20s %10d", getLastName(), getFirstName(), getId());
    }


    @Override
    public boolean equals(Object object) {
        if (this == object) {
            return true;
        }
        if (!(object instanceof me.dokollari.course.manager.models.Instructor)) {
            return false;
        }
        final me.dokollari.course.manager.models.Instructor other =
            (me.dokollari.course.manager.models.Instructor) object;
        if (!(getLastName() == null ? other.getLastName() == null : getLastName().equals(other.getLastName()))) {
            return false;
        }
        if (!(getFirstName() == null ? other.getFirstName() == null : getFirstName().equals(other.getFirstName()))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int PRIME = 37;
        int result = 1;
        result = PRIME * result + ((getLastName() == null) ? 0 : getLastName().hashCode());
        result = PRIME * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        return result;
    }
}

